services:
  mysql:
    image: mysql:8.4
    container_name: car-rental-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_rental_db
      MYSQL_USER: car_rental_user
      MYSQL_PASSWORD: car_rental_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
